name: Android Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set Up JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run Login Tests
        run: ./gradlew :app:feature_login:test

      - name: Run App Tests
        run: ./gradlew :app:test

      - name: Build Project
        run: ./gradlew :app:build
        
